# Generated by Django 2.2.3 on 2020-08-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200804_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationgroup',
            name='method_of_procurement',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
