# Generated by Django 2.2.3 on 2020-08-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consolidationgroup_method_of_procurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='expense',
        ),
    ]
