# Generated by Django 2.2.3 on 2020-08-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consolidationgroup_expense'),
        ('planning', '0002_auto_20200805_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsolidationGroup',
        ),
    ]
