# Generated by Django 2.2.3 on 2020-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_consolidationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='award_notification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='bid_evaluation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='bid_invitation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='bid_opening_and_closing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='board_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='cc_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='contract_completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='contract_signing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='plans_published_on',
            field=models.DateField(null=True),
        ),
    ]
