# Generated by Django 2.2.3 on 2020-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200805_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='award_notification_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='bid_evaluation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='bid_invitation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='bid_opening_and_closing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='contract_completion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='contract_signing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='plans_published_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='submission_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
