# Generated by Django 2.2.3 on 2020-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200810_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='stop',
            field=models.DateTimeField(null=True),
        ),
    ]
