# Generated by Django 2.2.3 on 2020-08-20 01:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200810_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdepartment',
            name='budget_sealing',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2020, 8, 21, 1, 10, 34, 205265, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
