# Generated by Django 2.2.3 on 2020-08-21 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200820_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartment',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 2, 17, 33, 355904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
