# Generated by Django 2.2.3 on 2020-08-21 02:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200821_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 2, 22, 42, 472054, tzinfo=utc)),
        ),
    ]
