# Generated by Django 2.2.3 on 2020-08-21 02:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200821_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 2, 40, 57, 860745, tzinfo=utc)),
        ),
    ]
