# Generated by Django 2.2.3 on 2020-08-21 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200821_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
