# Generated by Django 2.2.3 on 2020-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200821_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type_of_procurement',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
