# Generated by Django 2.2.3 on 2020-08-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_expense_type_of_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type_of_procurement',
            field=models.CharField(default='SUPPLIES', max_length=128),
            preserve_default=False,
        ),
    ]
