# Generated by Django 2.2.3 on 2020-08-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(max_length=128, null=True)),
                ('subject_of_procurement', models.CharField(max_length=128)),
                ('type_of_procurement', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=32)),
                ('estimated_cost', models.IntegerField()),
                ('source_of_funding', models.CharField(max_length=64)),
                ('date_required_q1', models.BooleanField()),
                ('date_required_q2', models.BooleanField()),
                ('date_required_q3', models.BooleanField()),
                ('date_required_q4', models.BooleanField()),
                ('prepared_on', models.DateField(null=True)),
                ('hod_approved_on', models.DateField(null=True)),
                ('pdu_approved_on', models.DateField(null=True)),
                ('consolidated_on', models.DateField(null=True)),
                ('stage', models.CharField(default='PREPARATION', max_length=16)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('consolidation_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConsolidationGroup')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Expense')),
                ('incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incharge_plan_set', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_plan_set', to=settings.AUTH_USER_MODEL)),
                ('user_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('corrected', models.BooleanField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=512, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
