# Generated by Django 2.2.3 on 2020-09-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_procurement', models.CharField(max_length=128, null=True)),
                ('procurement_type', models.CharField(max_length=128)),
                ('method_of_procurement', models.CharField(max_length=128, null=True)),
                ('contract_type', models.CharField(max_length=64, null=True)),
                ('prequalification', models.BooleanField(null=True)),
                ('bid_invitation_date', models.DateTimeField(null=True)),
                ('bid_opening_and_closing_date', models.DateTimeField(null=True)),
                ('bid_evaluation_date', models.DateTimeField(null=True)),
                ('award_notification_date', models.DateTimeField(null=True)),
                ('contract_signing_date', models.DateTimeField(null=True)),
                ('contract_completion_date', models.DateTimeField(null=True)),
                ('preparation_of_bid_document', models.DateTimeField(null=True)),
                ('approval_of_bid_document', models.DateTimeField(null=True)),
                ('invitation_bid', models.DateTimeField(null=True)),
                ('issue_and_sale_of_bid_document', models.DateTimeField(null=True)),
                ('receiof_bids', models.DateTimeField(null=True)),
                ('opening_of_bids', models.DateTimeField(null=True)),
                ('nomination_of_evaluation_committee_members', models.DateTimeField(null=True)),
                ('approval_or_rejection_of_evaluation_committee_members', models.DateTimeField(null=True)),
                ('evaluation_of_bids', models.DateTimeField(null=True)),
                ('approval_or_rejection_of_evaluation_report', models.DateTimeField(null=True)),
                ('display_of_best_evaluated_bidders', models.DateTimeField(null=True)),
                ('contract_signing', models.DateTimeField(null=True)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(max_length=128, null=True)),
                ('subject_of_procurement', models.CharField(max_length=128)),
                ('procurement_type', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=32)),
                ('estimated_cost', models.IntegerField()),
                ('date_required_q1', models.BooleanField()),
                ('date_required_q2', models.BooleanField()),
                ('date_required_q3', models.BooleanField()),
                ('date_required_q4', models.BooleanField()),
                ('prepared_on', models.DateField(null=True)),
                ('hod_approved_on', models.DateField(null=True)),
                ('pdu_approved_on', models.DateField(null=True)),
                ('consolidated_on', models.DateField(null=True)),
                ('published_on', models.DateField(null=True)),
                ('stage', models.CharField(default='PREPARATION', max_length=16)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('consolidation_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.ConsolidationGroup')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Expense')),
                ('incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incharge_plan_set', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_plan_set', to=settings.AUTH_USER_MODEL)),
                ('source_of_funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funder')),
                ('user_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('corrected', models.BooleanField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=512, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
