# Generated by Django 2.2.3 on 2020-09-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidationgroup',
            name='procurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProcurementType'),
        ),
    ]
