# Generated by Django 2.2.3 on 2020-08-05 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consolidationgroup_expense'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_procurement', models.CharField(max_length=128, null=True)),
                ('method_of_procurement', models.CharField(max_length=128, null=True)),
                ('contract_type', models.CharField(max_length=64, null=True)),
                ('prequalification', models.BooleanField(null=True)),
                ('bid_invitation_date', models.DateTimeField(null=True)),
                ('bid_opening_and_closing_date', models.DateTimeField(null=True)),
                ('bid_evaluation_date', models.DateTimeField(null=True)),
                ('award_notification_date', models.DateTimeField(null=True)),
                ('contract_signing_date', models.DateTimeField(null=True)),
                ('contract_completion_date', models.DateTimeField(null=True)),
                ('expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Expense')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='consolidation_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.ConsolidationGroup'),
        ),
    ]
