# Generated by Django 2.2.3 on 2020-08-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_projectconsolidationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationgroup',
            name='source_of_funding',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectConsolidationGroup',
        ),
    ]
