# Generated by Django 2.2.3 on 2020-10-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20200929_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='estimated_cost',
            new_name='estimated_unit_cost',
        ),
    ]
