# Generated by Django 2.2.3 on 2020-08-05 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20200805_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidationgroup',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Expense'),
        ),
    ]
