# Generated by Django 2.2.3 on 2020-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_plan_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationgroup',
            name='type_of_procurement',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
