# Generated by Django 2.2.3 on 2020-08-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_consolidationgroup_type_of_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='source_of_funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funder'),
        ),
    ]
