# Generated by Django 2.2.3 on 2020-08-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20200823_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidationgroup',
            name='type_of_procurement',
            field=models.CharField(default='SUPPLIES', max_length=128),
            preserve_default=False,
        ),
    ]
