# Generated by Django 2.2.3 on 2020-08-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_auto_20200826_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_approval_of_bid_document',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_approval_or_rejection_of_evaluation_committee_members',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_approval_or_rejection_of_evaluation_report',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_contract_signing',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_display_of_best_evaluated_bidders',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_evaluation_of_bids',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_invitation_bid',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_issue_and_sale_of_bid_document',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_nomination_of_evaluation_committee_members',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_opening_of_bids',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_preparation_of_bid_document',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='pt_receipt_of_bids',
        ),
        migrations.CreateModel(
            name='ProcessTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_preparation_of_bid_document', models.DateTimeField(null=True)),
                ('pt_approval_of_bid_document', models.DateTimeField(null=True)),
                ('pt_invitation_bid', models.DateTimeField(null=True)),
                ('pt_issue_and_sale_of_bid_document', models.DateTimeField(null=True)),
                ('pt_receipt_of_bids', models.DateTimeField(null=True)),
                ('pt_opening_of_bids', models.DateTimeField(null=True)),
                ('pt_nomination_of_evaluation_committee_members', models.DateTimeField(null=True)),
                ('pt_approval_or_rejection_of_evaluation_committee_members', models.DateTimeField(null=True)),
                ('pt_evaluation_of_bids', models.DateTimeField(null=True)),
                ('pt_approval_or_rejection_of_evaluation_report', models.DateTimeField(null=True)),
                ('pt_display_of_best_evaluated_bidders', models.DateTimeField(null=True)),
                ('pt_contract_signing', models.DateTimeField(null=True)),
                ('consolidation_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planning.ConsolidationGroup')),
            ],
        ),
    ]
