# Generated by Django 2.2.3 on 2020-08-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_auto_20200826_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_approval_of_bid_document',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_approval_or_rejection_of_evaluation_committee_members',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_approval_or_rejection_of_evaluation_report',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_contract_signing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_display_of_best_evaluated_bidders',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_evaluation_of_bids',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_invitation_bid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_issue_and_sale_of_bid_document',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_nomination_of_evaluation_committee_members',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_opening_of_bids',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_preparation_of_bid_document',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consolidationgroup',
            name='pt_receipt_of_bids',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='ProcessTrack',
        ),
    ]
