# Generated by Django 2.2.3 on 2020-08-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_auto_20200826_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_approval_of_bid_document',
            new_name='approval_of_bid_document',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_approval_or_rejection_of_evaluation_committee_members',
            new_name='approval_or_rejection_of_evaluation_committee_members',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_approval_or_rejection_of_evaluation_report',
            new_name='approval_or_rejection_of_evaluation_report',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_contract_signing',
            new_name='contract_signing',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_display_of_best_evaluated_bidders',
            new_name='display_of_best_evaluated_bidders',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_evaluation_of_bids',
            new_name='evaluation_of_bids',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_invitation_bid',
            new_name='invitation_bid',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_issue_and_sale_of_bid_document',
            new_name='issue_and_sale_of_bid_document',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_nomination_of_evaluation_committee_members',
            new_name='nomination_of_evaluation_committee_members',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_opening_of_bids',
            new_name='opening_of_bids',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_preparation_of_bid_document',
            new_name='preparation_of_bid_document',
        ),
        migrations.RenameField(
            model_name='consolidationgroup',
            old_name='pt_receipt_of_bids',
            new_name='receiof_bids',
        ),
    ]
