# Generated by Django 2.2.3 on 2020-09-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(max_length=128, null=True)),
                ('sequence_number', models.CharField(max_length=128, null=True)),
                ('subject_of_procurement', models.CharField(max_length=128)),
                ('type_of_procurement', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=32)),
                ('estimated_cost', models.IntegerField()),
                ('date_required_q1', models.BooleanField(default=False)),
                ('date_required_q2', models.BooleanField(default=False)),
                ('date_required_q3', models.BooleanField(default=False)),
                ('date_required_q4', models.BooleanField(default=False)),
                ('stage', models.CharField(default='INITIATION', max_length=64)),
                ('location_of_delivery', models.CharField(max_length=128)),
                ('file_attachment', models.FileField(null=True, upload_to='')),
                ('specified_on', models.DateField(null=True)),
                ('hod_approved_on', models.DateField(null=True)),
                ('pdu_approved_on', models.DateField(null=True)),
                ('ao_approved_on', models.DateField(null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Expense')),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incharge_requisition_set', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_requisition_set', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Plan')),
                ('source_of_funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funder')),
                ('user_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiation.Requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('corrected', models.BooleanField(null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiation.Requisition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=512, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiation.Requisition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
