# Generated by Django 2.2.3 on 2020-09-12 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200911_1239'),
        ('initiation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='type_of_procurement',
        ),
        migrations.AddField(
            model_name='requisition',
            name='procurement_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ProcurementType'),
            preserve_default=False,
        ),
    ]
