# Generated by Django 2.2.3 on 2020-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequisitionCorrection',
        ),
    ]
