# Generated by Django 2.2.3 on 2020-09-13 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0002_auto_20200912_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='file_attachment',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='requisition',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=64)),
                ('unit_cost', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(null=True, upload_to='')),
                ('requisition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiation.Requisition')),
            ],
        ),
        migrations.AddField(
            model_name='specification',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initiation.Item'),
            preserve_default=False,
        ),
    ]
