# Generated by Django 2.2.3 on 2020-08-06 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiation', '0002_delete_requisitioncorrection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequisitionsCorrection',
            new_name='RequisitionCorrection',
        ),
    ]
