# Generated by Django 2.2.3 on 2020-09-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0003_auto_20200913_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='requisition_id',
            new_name='requisition',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='item_id',
            new_name='item',
        ),
    ]
