# Generated by Django 2.2.3 on 2020-08-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0003_auto_20200806_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='file_attachement_location',
            new_name='file_attachement',
        ),
    ]
