# Generated by Django 2.2.3 on 2020-09-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0004_auto_20200913_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=64)),
                ('estimated_unit_cost', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Specification',
            new_name='AttributeValueSpecification',
        ),
        migrations.RemoveField(
            model_name='attributevaluespecification',
            name='item',
        ),
        migrations.AddField(
            model_name='attributevaluespecification',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initiation.Requisition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='description',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='file_specification',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='stage',
            field=models.CharField(default='REQUIREMENTS SPECIFICATION', max_length=64),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiation.Requisition'),
        ),
    ]
