# Generated by Django 2.2.3 on 2020-08-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0004_auto_20200806_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='alt_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_required_q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_required_q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_required_q3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_required_q4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='delivery_location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='file_attachement',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sequence_number',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
