# Generated by Django 2.2.3 on 2020-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0005_auto_20200917_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
