# Generated by Django 2.2.3 on 2020-08-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200805_0940'),
        ('initiation', '0005_auto_20200806_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='user_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserDepartment'),
            preserve_default=False,
        ),
    ]
