# Generated by Django 2.2.3 on 2020-10-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0006_auto_20200917_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='specified_on',
            new_name='specified_on',
        ),
    ]
