# Generated by Django 2.2.3 on 2020-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0007_auto_20201003_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='stage',
            field=models.CharField(default='REQUIREMENTS SPECIFICATION', max_length=64, null=True),
        ),
    ]
