# Generated by Django 2.2.3 on 2020-08-07 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0007_auto_20200807_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incharge_requisition_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
