# Generated by Django 2.2.3 on 2020-08-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0008_auto_20200807_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='file_attachement',
        ),
        migrations.AddField(
            model_name='requisition',
            name='file_attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
