# Generated by Django 2.2.3 on 2020-10-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0008_auto_20201003_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planning.Plan'),
        ),
    ]
