# Generated by Django 2.2.3 on 2020-08-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0010_auto_20200808_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='stage',
            field=models.CharField(default='INITIATION', max_length=64),
        ),
    ]
