# Generated by Django 2.2.3 on 2020-08-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200805_0940'),
        ('initiation', '0011_requisition_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='expense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Expense'),
            preserve_default=False,
        ),
    ]
