# Generated by Django 2.2.3 on 2020-08-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0012_requisition_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='initiated_on',
            field=models.DateField(null=True),
        ),
    ]
