# Generated by Django 2.2.3 on 2020-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0013_requisition_initiated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='delivery_location',
        ),
        migrations.AddField(
            model_name='requisition',
            name='location_of_delivery',
            field=models.CharField(default='Muni University', max_length=128),
            preserve_default=False,
        ),
    ]
